import java.util.List;
/**
 * Contains a single method which creates list of possible moves
 * a rook can make which is later refined by PostMoveValidator.
 */
public class RookMovesGen extends MovesGenerator {
    /**
     * Checks if rook can move seven squares along any cardinal
     * straight line. Any moves which jump over a piece,
     * are not on the board, or are occupied by a friendly
     * piece are removed from the list. King checks are NOT
     * considered at this stage.
     *
     * @param board the board on which moves are generated
     * @param rook the rook piece for which moves are generated
     * @return the list of possible moves
     */
    @Override
    public List<Move> generate (Board board, Piece rook) {
        int[] origin = rook.getCoords();
        //The coordinate changes corresponding to each of the cardinals along which
        //rooks can move
        int[][] directions = {{-1, 0}, {0, 1}, {1, 0}, {0, -1}};
        //Moves generated by helper method in MovesGenerator and returned
        return genStraightLineMoves(origin, directions, board);
    }
}
